"""add_item_type_to_item

Revision ID: 44b6a9196e68
Revises: 1a31ce608336
Create Date: 2025-10-20 05:55:01.751116

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '44b6a9196e68'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.execute("UPDATE item SET item_type = 'Personal' WHERE item_type IS NULL")
    op.alter_column('item', 'item_type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'item_type')
    # ### end Alembic commands ###
