name: Docs CI

on:
  pull_request:
    paths:
      - "**.md"
      - ".github/workflows/docs-ci.yml"
      - ".markdownlint.json"
      - ".mlc_config.json"

jobs:
  lint-and-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install markdown tools
        run: |
          npm install -g markdownlint-cli2 markdown-link-check

      - name: Lint markdown files
        run: markdownlint-cli2 "**/*.md"

      - name: Check links in markdown files
        run: |
          set -e
          find . -name "*.md" -not -path "./node_modules/*" -not -path "./.git/*" -print0 | \
            xargs -0 -n1 markdown-link-check --config .mlc_config.json -q || true
        continue-on-error: true
